### FrontEnd

http://localhost:5173


### Health check

http://localhost:3000/health


### items test

### post one item into db
POST http://localhost:3000/add HTTP/1.1
Content-Type: application/json

{
  id: "732673267"
  content: "Some foo content to try thi is working or not?"
}